export const EXPENSE_CATEGORY_LIST = [
  { value: "alimentation", label: "Alimentation" },
  { value: "habillement", label: "Habillement" },
  { value: "cadeaux", label: "Cadeaux" },
  { value: "internetTvTelephone", label: "Internet / TV / Téléphone" },
  { value: "sports", label: "Sports" },
  { value: "loisir", label: "Loisir" },
  { value: "formation", label: "Formation" },
  { value: "enfants", label: "Enfants" },
  { value: "impots", label: "Impôts" },
  { value: "transports", label: "Transports" },
  { value: "restaurationHotel", label: "Restauration / Hotel" },
  { value: "service", label: "Service" },
  { value: "sante", label: "Santé" },
  { value: "etf", label: "ETF" },
  { value: "autres", label: "Autres" },
];

export const BUDGET_STYLE = [
  {
    budgetCategory: "GLOBAL",
    label: "Général",
    displayCurrentAmount: false,
    displayProgressBar: true,
    bgColor: "purple.200",
    colStart: "3",
    colEnd: "7",
  },
  {
    budgetCategory: "INVESTISSEMENT",
    label: "Investissement",
    displayCurrentAmount: true,
    displayProgressBar: false,
    bgColor: "blue.200",
    colSpan: "1",
    colStart: "3",
    colEnd: "",
  },
  {
    budgetCategory: "OBLIGATOIRE",
    label: "Obligatoire",
    displayCurrentAmount: false,
    displayProgressBar: true,
    bgColor: "orange.200",
    colSpan: "2",
    colStart: "",
    colEnd: "",
  },
  {
    budgetCategory: "LOISIR",
    label: "Loisir",
    displayCurrentAmount: false,
    displayProgressBar: true,
    bgColor: "green.200",
    colSpan: "1",
    colStart: "",
    colEnd: "",
  },
];

export const BUDGET_CATEGORIES = {
  GLOBAL: {
    category: [
      "alimentation",
      "habillement",
      "cadeaux",
      "internetTvTelephone",
      "sports",
      "loisir",
      "formation",
      "enfants",
      "impots",
      "transports",
      "restaurationHotel",
      "service",
      "sante",
      "etf",
      "autres",
    ],
  },
  INVESTISSEMENT: {
    category: ["etf"],
  },
  OBLIGATOIRE: {
    category: [
      "alimentation",
      "sante",
      "internetTvTelephone",
      "enfants",
      "impôts",
    ],
  },
  LOISIR: {
    category: [
      "cadeaux",
      "habillement",
      "sports",
      "restaurationHotel",
      "transports",
      "loisir",
    ],
  },
};
