export const EXPENSE_CATEGORY_LIST = [
  { value: "alimentation", label: "Alimentation" },
  { value: "habillement", label: "Habillement" },
  { value: "cadeaux", label: "Cadeaux" },
  { value: "internetTvTelephone", label: "Internet / TV / Téléphone" },
  { value: "sports", label: "Sports" },
  { value: "loisir", label: "Loisir" },
  { value: "formation", label: "Formation" },
  { value: "enfants", label: "Enfants" },
  { value: "impots", label: "Impôts" },
  { value: "transports", label: "Transports" },
  { value: "restaurationHotel", label: "Restauration / Hotel" },
  { value: "service", label: "Service" },
  { value: "sante", label: "Santé" },
  { value: "autres", label: "Autres" },
];

export const BUDGET_STYLE = [
  {
    budgetCategory: "Global",
    displayCurrentAmount: false,
    displayProgressBar: true,
    bgColor: "purple.200",
    colSpan: "4",
    colStart: "2",
    colEnd: "8",
  },
  {
    budgetCategory: "Investissement",
    displayCurrentAmount: false,
    displayProgressBar: true,
    bgColor: "blue.200",
    colSpan: "2",
    colStart: "2",
    colEnd: "",
  },
  {
    budgetCategory: "Obligatoire",
    displayCurrentAmount: false,
    displayProgressBar: true,
    bgColor: "orange.200",
    colSpan: "2",
    colStart: "",
    colEnd: "",
  },
  {
    budgetCategory: "Loisir",
    displayCurrentAmount: false,
    displayProgressBar: true,
    bgColor: "green.200",
    colSpan: "2",
    colStart: "",
    colEnd: "",
  },
];

export const BUDGET_CATEGORIES = [
  {
    budgetCategory: "Global",
    currentAmount: 400,
    max: 1000,
    displayCurrentAmount: false,
    displayProgressBar: true,
  },
  {
    budgetCategory: "Investissement",
    expenses: ["factures", "sante"],
    currentAmount: 400,
    max: 1000,
    displayCurrentAmount: false,
    displayProgressBar: true,
  },
  {
    budgetCategory: "Obligatoire",
    expenses: [
      "alimentation",
      "factures",
      "sante",
      "internetTvTelephone",
      "enfants",
      "impôts",
    ],
    currentAmount: 200,
    max: 1000,
    displayCurrentAmount: false,
    displayProgressBar: true,
  },
  {
    budgetCategory: "Loisir",
    expenses: [
      "cadeaux",
      "habillement",
      "sports",
      "restaurationHotel",
      "transports",
    ],
    currentAmount: 800,
    max: 1000,
    displayCurrentAmount: false,
    displayProgressBar: true,
  },
];
